# Generated by Django 5.1.1 on 2024-09-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_carrito_carritoitem_carrito_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
