# Generated by Django 5.1.1 on 2024-09-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_remove_carritoitem_carrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='descripcion_lesion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='descripcion_procedimiento_medico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='eps',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_clientes/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='objetivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tiene_lesion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tiene_procedimiento_medico',
            field=models.BooleanField(default=False),
        ),
    ]
